name: Statistics
main: com.github.etsija.statistics.Statistics
version: 0.3
depend: [Vault, SQLibrary]
commands:
   stats:
      description: This command gives some stats of a player
      usage: /<command> [user/self/new/newp/since]
      permission: statistics.stats
      permission-message: You don't have <permission> permission.